### ISSUE TITLE
Shorts, Threes, and Ints aren’t unsigned

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#149]
Noticed while testing this with reoserv that the client reads shorts, threes, and ints as signed values.

This became an issue when reoserv tried to send a a session id that was bigger than a signed short can hold.

I tried fixing this myself but it quickly became a huge change to over 100 files and broke a lot of stuff.

**Comment by ethanmoffat** [comment]
Yeah this is a big problem. I also went through and tried to update it to use signed values and had the same issue, 100+ files changed quickly became a headache.

The actual problem is that because `NumberEncoderService` takes an `int`, it will sign extend `short`s that are greater than `short.MaxValue`. See: b80ff5ceea98ab0f1517a18f8c7a38e8dab4a280

What I ended up doing to resolve it is just casting to `ushort` client-side. It's an ugly hack but it works. 

Which session id specifically was causing the issue?

**Comment by sorokya** [comment]
In reoserv I generate a random short value between 0 and the max2 value.

https://github.com/sorokya/reoserv/blob/async-rewrite/src/player/player.rs#L154

the error was coming up during the welcome message packet. The session id reoserv sent was too big.

**Comment by ethanmoffat** [comment]
I'll see if I can reproduce it against reoserv. That commit I linked (b80ff5ceea98ab0f1517a18f8c7a38e8dab4a280) was working for me with larger player IDs on GameServer and etheos

**Comment by sorokya** [comment]
Ah you’re right casting it back to unsigned does fix it. I’ll just do that for now in my branch. :P

**Comment by ethanmoffat** [comment]
I didn't have that issue for shorts in my testing. I also added a line to `PacketBuilder` that casts the `short` to `ushort` prior to calling `EncodeNumber` with it so it doesn't get sign-extended during encoding: https://github.com/ethanmoffat/EndlessClient/blob/5fa705fa1c38f5961ad389a69399f2b84d27d624/EOLib/Net/PacketBuilder.cs#L70

I forgot I updated it in both these places, but it was working consistently for me on both etheos and gameserver

**Comment by sorokya** [comment]
You're right that totally fixes it. No need for the overload :)

**Comment by ethanmoffat** [comment]
When playing on BU, this problem is pretty apparent once you get over `TWO_BYTE_MAX` HP:
<img width="122" alt="image" src="https://user-images.githubusercontent.com/8301078/196003296-58d40dd7-641e-48c2-86ef-6beb7f0a7a18.png">

Adding the `ushort` cast fixes it but we need a more universal solution because that's gross and hacky.

**Comment by ethanmoffat** [comment]
I'm going to take the `eolib-java` approach and make everything an `int` instead of using exotic types.
