### ISSUE TITLE
Chat buffer isn't cleared between logins

### ISSUE THREAD

**Issue by sorokya** [ethanmoffat/EndlessClient#151]
When logging in multiple times without closing the client the server MOTD and global chat rules appear to duplicate for each login

<img width="481" alt="EndlessClient_MeR7aQT7JU" src="https://user-images.githubusercontent.com/3664832/160231249-1b83c3c7-527d-462a-a1e5-07f172151b3e.png">
<img width="481" alt="EndlessClient_TMe6XWZsdS" src="https://user-images.githubusercontent.com/3664832/160231252-a9478512-0f1f-4fde-a959-805ff04ddeb0.png">

Edit: Looks like chat messages persist as well

**Comment by ethanmoffat** [comment]
This is a known issue I've had for a while, I guess I never got around to actually filing an issue for it. I implemented a pattern for this via `IResettable` - the chat repository *should* be cleared after each login, but it isn't because of a bug in `AutomaticTypeMapper` (really in Unity's handling of binding the types that I couldn't get them to fix). When the interface and implementation exist across assemblies, it isn't treating them as the same singleton instance in the dependency container, so `IResettable` gets called but doesn't hit the same instance as is used for displaying chat like it should.
