### ISSUE TITLE
@Announcement chat, +Admin chat, possible NPC rendering crash?

### ISSUE THREAD

**Issue by Septharoth** [ethanmoffat/EndlessClient#20]
This isn't a bug, as it looks as if you just haven't added it quite yet.  (Unless you've added it in a more recent commit that I missed)

But, @Announcements don't come up when used.  Also +Admin chat isn't implemented yet I suppose?  I'll be compiling your next commit and finding as many bugs as I can.

Also, when around NPCs, it seems the game crashes.  I've AFK'd for hours in the first map, as soon as I walked out the room it crashed.  Although, it could have something to do with the size of the map?  I'm completely unsure of the cause, but it seems as if it's NPCs causing said crash.

**Comment by ethanmoffat** [comment]
Yeah, I haven't done admin chat yet. I think the game crashing after walking out of the room is related to some weird stuff going on with Warp packets. Sometimes the map doesn't get loaded properly after a WARP_TAKE (which loads the new map). The latest build has a better error message for that case instead of just crashing the game. NPC stuff should be improved in the latest build too.

**Comment by Septharoth** [comment]
There might be another bug with the warp packets.

But, I'm talking when I'm sitting on the map with NPCs I'll just crash randomly.  but, I have to recompile the current build to see if it's still happening to me.

**Comment by ethanmoffat** [comment]
I've added support for the other chat types, at least for '@' and '+' talking. Latest commit: 260fd3a

If you're having issue with Warp packets or NPCs and have something that's reproducable, file it in a separate issue - I want to try to keep issues focused on single items if possible :P
