### ISSUE TITLE
Font issue?

### ISSUE THREAD

**Issue by dgadelha** [ethanmoffat/EndlessClient#26]
I don't know if it's related to a change I did to remove HiDef to avoid this issue:
![issue_0](https://cloud.githubusercontent.com/assets/10081640/9192443/8bbbdcba-3fe1-11e5-9e01-db92ddc4c737.png)
But I'm living on this font bug:
![issue](https://cloud.githubusercontent.com/assets/10081640/9192412/42b745ea-3fe1-11e5-9e3b-e6bdc4ac3871.png)

**Comment by dgadelha** [comment]
Oh, also tried to set BackColor to Transparent, and it got worse.

**Comment by ethanmoffat** [comment]
Are you developing in a VM? That's the only time I've had that issue (MessageBox that you screencapped), because hardware acceleration is disabled. Development in a VM is not supported.

Also if you're on Win10 I haven't tested anything for that yet, and I know there are other graphics driver issues reported on eoserv.net for the regular client. I have an AMD GPU (I think the issues were for NVIDIA cards)

The font bug, I haven't come across - but it may be related to the above issues that I mentioned. One of my friends changed the development to use System.Drawing for font rendering which might cause some unknown issues.

Checking out your pull request for testing, I noticed that the font rendered improperly for me when set to "Segoe UI" but "Segoe UI Regular" worked fine. I'm guessing you may have a missing font (which is weird since I think Microsoft Sans Serif is standard in Windows...)

**Comment by dgadelha** [comment]
I'm developing on a real machine, with an old graphics card. That's why it won't run on HiDef

**Comment by ethanmoffat** [comment]
Do you have up-to-date drivers? Also what OS are you on (can't tell from the screenshot) and what GPU is it exactly? You should be able to see GPU info in dxdiag.exe

I'd like to investigate this since it's very likely an issue with how I do fonts but it seems tied to your specific system

**Comment by dgadelha** [comment]
>> Latest supported graphics version.

![dx1](https://cloud.githubusercontent.com/assets/10081640/9239365/5b19de58-4131-11e5-8429-0ed2b0be6f55.png)

![dx2](https://cloud.githubusercontent.com/assets/10081640/9239369/5d029ec6-4131-11e5-8e53-c4e6beab8f94.png)

**Comment by dgadelha** [comment]
The font on **EOScrollingDialog** works great, can you check how to implement everywhere?
Look below, text on text box is "bugged" and, at EOScrollingDialog isn't. The issue can be on your *XNAControls*.**XNALabel**.

![eo](https://cloud.githubusercontent.com/assets/10081640/9241962/bc9e79ee-4150-11e5-989d-732fd7edf30a.png)

**Comment by dgadelha** [comment]
Value of Game.DrawText() on XNALabel's GenerateImage:

![](https://cloud.githubusercontent.com/assets/10081640/9242477/0c94cdf2-4158-11e5-8d03-3276f2808a90.png)

As you see, even the text being Magenta, it looks shitty and looks like it has a Black background.
This can be related to HiDef, as I said, 'cause it's related to XNAFramework.Game.DrawText, but I think we can work on a fix for this, or test if on MonoGame this resolves.

**Comment by ethanmoffat** [comment]
I think EOScrollingDialog uses XNA / SpriteFont to render fonts, which might have an effect. XNALabel uses System.Drawing. I'm going to build out a Windows 10 VM to investigate and test this, but it may take a couple of days. I also don't see why your GPU shouldn't be able to handle rendering the game in HiDef.

Also see [this topic on eoserv.net](http://eoserv.net/forum/topic/23288) - apparently Windows 10 and NVIDIA don't play nicely yet. (or requires a patch)

**Comment by dgadelha** [comment]
Well, bad thing is that original EO client works good, while this doesn't.

**Comment by Rubes** [comment]
I'm getting this issue too on Windows 7. An older version of the client that I had on my computer works, though.

**Comment by dgadelha** [comment]
I guess label should be changed to confirmed then.

**Comment by Rubes** [comment]
Yeah. The client I have from 5/13/15 displays everything correctly but the newest version doesn't. I've fiddled with it a lot and still end up with a choppy outline.

**Comment by ethanmoffat** [comment]
Hmmm. That's annoying. I think the only thing I've changed since then is removing the Text Rendering Hint because I couldn't see a purpose to it. That might be what's causing it.

I still don't have a system I can test this on, since it works fine on my computer. Hopefully when I upgrade to Win10 it breaks for me too.

**Comment by dgadelha** [comment]
News?

**Comment by ethanmoffat** [comment]
I haven't had a chance to play around on Win10 yet. I'm hesitant to upgrade my primary dev environment because I've heard there are other issues with it.

I'll have a dedicated Win10 machine pretty soon that I can test this on and hopefully resolve.

**Comment by squiblez** [comment]
If I'm not mistaken, this client was based on EODev no? I had this issue on 3 ATI machines, and an Intel. But I also tested it on an older nVidea budget GPU that didn't have the same problem. I also have it happening now on Windows 7, with my R7 260x but not on an HD6450 1gb.

**Comment by ethanmoffat** [comment]
> If I'm not mistaken, this client was based on EODev no?

Not at all, it's built from scratch from the ground up. I used Hotdog's and Exile's sources as a reference for some rendering related things, and decompiled some of the EOSERV# libraries for packet things, but everything else I wrote myself.

> I had this issue on 3 ATI machines, and an Intel. But I also tested it on an older nVidea budget GPU that didn't have the same problem. I also have it happening now on Windows 7, with my R7 260x but not on an HD6450 1gb.

Interesting. My build is getting outdated, I run an XFX Radeon HD 6770 GPU and an AMD Phenom II X2 560 CPU, Win8.1 x64 w/ VS2013.

I'll see about changing to using SpriteFont instead of System.Drawing for XNALabel. I'm thinking more and more that's probably the cause - perhaps newer graphics hardware just won't work with that method of font rendering.

**Comment by ethanmoffat** [comment]
Good news everyone, I've successfully reproduced the font error on my Windows 10/VS2015 system! So I can actually work on this bug now.

**Comment by dgadelha** [comment]
Lol, finally, Windows 10 FTL XD

**Comment by Rubes** [comment]
Can't wait till this gets fixed, good luck

**Comment by ethanmoffat** [comment]
I'm getting pretty close. It involved a pretty big refactor of XNAControls. I'm cleaning up a few remaining display bugs but should have it in within the next couple of days.

**Comment by Rubes** [comment]
Looking forward to the update!

**Comment by dgadelha** [comment]
yay!

**Comment by ethanmoffat** [comment]
Still a few remaining display bugs to clean up but the majority of work for this is done. Other remaining bugs are most likely due to issues with XNAControls.

Commit 9679936
