### ISSUE TITLE
MonoGame

### ISSUE THREAD

**Issue by dgadelha** [ethanmoffat/EndlessClient#27]
Any chance to use MonoGame (http://www.monogame.net/ [XNA port in Mono]) instead of native XNA?
It will make possible the client to run on Linux/Mac using Mono, and also, mobile devices.

**Comment by ethanmoffat** [comment]
I've considered converting to MonoGame for exactly that reason. However, I rely on a couple of Win32 calls via p/invoke (for the HDD serial, GFX loading, and logging functions at the very least) that wouldn't be able to port over.

Unless you know of a way that I could make those p/invoke calls from MonoGame on alternate platforms?

**Comment by dgadelha** [comment]
You could try using a Unique ID for Device, instead of HDD ID, and there's no native function to Load GFX? Logging is pretty easy, just use some filesystem class.

**Comment by ethanmoffat** [comment]
Yeah take a look at GFXLoader.cs - that's my primary concern since it's kind of important to have graphics :)

Regarding HDD ID, I'm not super concerned about replacing it for some platform independence.

For logging, I use native calls for getting Process/Thread IDs. Those could also probably be converted or removed pretty easily, I don't think they're super important.

**Comment by dgadelha** [comment]
>> http://www.mono-project.com/docs/advanced/pinvoke/
>> http://www.gamedev.net/topic/640849-port-xna-to-ios-step-by-step-using-monogame/?view=findpost&p=5047730

**Comment by ethanmoffat** [comment]
That's all well and good, but the GFX are stored as compiled resources that are Windows specific. There are no cross-platform libraries (again that I know of) that provide implementations of the Windows `LoadLibrary`, `LoadImage`, `FreeLibrary`, and `DeleteObject` that are in use by GFXLoader.

**Comment by dgadelha** [comment]
LoadLibrary + FreeLibrary => http://dimitry-i.blogspot.com.br/2013/01/mononet-how-to-dynamically-load-native.html
For LoadImage, what's about Porting from [Wine (open-source)](http://source.winehq.org/git/wine.git/blob/refs/heads/master:/dlls/user32/cursoricon.c) or [ReactOS](https://github.com/mirror/reactos/tree/master/reactos/win32ss/user/user32/windows)
And looks like Mono's GdiPlus supports [DeleteObject](https://github.com/mono/libgdiplus/blob/f18514c8babf20301f8bbd1f0cfd587ed48a480b/src/metafile.c#L298)

**Comment by ethanmoffat** [comment]
Interesting. I'll look into this when I get more time and try setting up a Linux VM with monogame. I didn't know there were open implementations of those functions

**Comment by ethanmoffat** [comment]
I'm running into a lot of issues while porting the code base to monogame (running in an Ubuntu 15.04 VM). I may consider porting to monogame on Windows first and then getting it running on Linux separately.

This issue will remain open but is very low priority (cross-platform compatibility is not the primary focus of this project).

**Comment by dgadelha** [comment]
You really should try on Windows first. The ".exe" that is generated on Windows (via Mono), works on Linux too hehe

**Comment by dgadelha** [comment]
Game is running on MonoGame
![](https://cloud.githubusercontent.com/assets/10081640/9288092/dd2e8606-430b-11e5-87f9-bb9c1c93d327.png)
And font doesn't look that bugged!
![](https://cloud.githubusercontent.com/assets/10081640/9288094/f2fe46ce-430b-11e5-9957-17242599b8c3.png)

**Comment by ethanmoffat** [comment]
Yeah I thought it was kind of funny :)

Not sure why that happens yet though. I'm working on getting the development environment set up and working on my Ubuntu 15.04 VM, then I'll focus on any bugs that have come into play.

**Comment by dgadelha** [comment]
Any updates?

**Comment by ethanmoffat** [comment]
Haven't had a chance to work on it recently - I'm hoping to make some time tonight or Saturday.

I'm running up against a content generation issue on Ubuntu. So I may put that on hold until I can get a dedicated Ubuntu machine (running a VM right now)

**Comment by ethanmoffat** [comment]
I've been investigating getting this built on Ubuntu 15.04. As expected, there are a few problems I've come across, mostly related to dependencies on the Windows API via P/Invoke:

1. GFX Files are Win32 PE Files. There is no native / built-in way to load images from these files on Linux - P/Invoke is used to load them on Windows, which works in mono because Kernel32.dll exists on Windows regardless of how the C# executable is built. GFX images would have to be extracted from the original files, or a custom PE loader would have to be written. This would either break support for the existing client (option a) or be extremely difficult (option b).
2. XNAControls uses a Win32 Keyboard hook (via P/Invoke) for input processing in text boxes. I haven't investigated very much, but using the native XNA/Monogame support would be less natural as far as typing is concerned, although very possible when compared with the GFX file problems.
3. Background music uses a System.Windows.Media.MediaPlayer object to play the MIDI files, which is basically a Windows Media Player instance. This is obviously not on Linux. Background music isn't  essential to the game, but it is definitely nice to have. I don't know a good replacement for this yet, playing MIDI files is not supported in XNA.
4. SpriteFonts aren't building correctly. I'm sure I'm just doing something wrong with the project setup, but for whatever reason the content builds the PNG images just fine and throws a vague error for the fonts.
5. Other P/Invoke functions - I think there are other P/Invoke functions used that would have to be replaced with different functionality on non-windows platforms. One example is the hard drive ID; things like this would be trivial to replace but more investigation is needed.

Fortunately I took out support of GDI drawing (System.Drawing.Graphics) in XNAControls and replaced it with native XNA stuff (SpriteBatch.DrawString), so this removes a lot of uncertainly. However, item 1 on the above list is a big enough problem that I don't think a cross-platform client is feasible without some serious work.

**Comment by ethanmoffat** [comment]
Stay tuned for Ubuntu support, I've written an open-source cross-platform PE loader ([here](https://github.com/ethanmoffat/PELoaderLib)) that should work on Ubuntu and doesn't rely on the P/Invoke functions LoadLibrary/LoadImage/etc.

Assuming I can replace all the windows-specific P/Invoke function calls, there should be a working Linux build in the near future!

**Comment by dgadelha** [comment]
Looks good, keep up!

**Comment by ethanmoffat** [comment]
Finally got this working in Ubuntu! See PR #81 

Sample:
https://cdn.discordapp.com/attachments/666280326938755072/669796361318694921/unknown.png
