### ISSUE TITLE
If you do not have space in your inventory for an item, making space for it does not make it appear like it does in vanilla

### ISSUE THREAD

**Issue by DanDecrypted** [ethanmoffat/EndlessClient#289]
Scenario: you have a 1x1 item in every top row of your inventory, you also have a twin blades on your account (2x5). You move two of the 1x1 items creating a free 2x5 space for your TB to fall into.

Expected: TB appears as soon as the second 1x1 item is moved making space for it.
Actual: Relog required.

I would expect this would involve tracking items that could not fit into your inventory on login & checking if there is now space for them when an item in your inventory is moved. The definition of "moved" is not having any items attached to your cursor so you are not forced to drop something.

**Comment by ethanmoffat** [comment]
I think this could potentially be pretty easy. Current behavior is COMPLIANT but I'd rather have inventory work better since it's one of the crappy parts about the vanilla client.

My idea for resolving this was to add a scrollbar, basically double the size of the inventory. I haven't thought too much about item scrolling. Even in that case you could still run out of space, so this change would be helpful in that situation as well.
