### ISSUE TITLE
EObot

### ISSUE THREAD

**Issue by itashi811** [ethanmoffat/EndlessClient#87]
Everything is compiled but when I run eobot.exe is closes automatically do you know whats wrong?

its saying invalid: please specify host, port and number of bots to run

**Comment by itashi811** [comment]
how to run the exe?

**Comment by ethanmoffat** [comment]
The error tells you exactly what's wrong. Look at the source: https://github.com/ethanmoffat/EndlessClient/blob/64dea093f452067d1c3f983f8c11b97fbafe6538/EOBot/Program.cs#L91

`eobot.exe host=<host> port=<port> ...`

I don't think EOBot has been updated since I started the client rewrite. It compiles but I'm not entirely sure it will run anymore without heavy modification.

**Comment by itashi811** [comment]
Okay, thank you for the reply

**Comment by itashi811** [comment]
How would I go about this heavy modification? And would it be hard to do so?

**Comment by ethanmoffat** [comment]
Closing this because EOBot has been updated to support the new code architecture. Check out the help message if you're interested in running scripts or the code in `TrainerBot.cs` if you want to annoy admins on a certain server
